App_Login/urls.py
from django.conf.urls import url
from django.urls import path
from App_Login import views

app_name='App_Login'

urlpatterns = [
    
    path('signup/',views.sign_up,name='signup'),
    path('login/',views.login_page,name='login'),
    path('logout/',views.logout_user,name='logout'),
    path('change_profile/',views.user_change,name='change_profile'),
    path('profile/',views.profile,name='profile'),
    path('add-picture',views.add_pro_pic,name='add_pro_pic'),
    path('change-picture/',views.change_pro_pic,name='change_pro_pic'),
    path('password/',views.pass_change,name='pass_change'),
]

Storage_Box/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('App_Login.urls')),
    path('upload/',include('Upload_App.urls')),
    path('',views.index,name='index'),
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfile(models.Model):
    user=models.OneToOneField(User, primary_key=True, related_name='user_profile',on_delete=models.CASCADE)
    profile_pic=models.ImageField(upload_to='profile_pics')

App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm ,UserChangeForm
from django.contrib.auth.models import User
from App_Login.models import  UserProfile

class SignUpForm(UserCreationForm):
    email=forms.EmailField(required=True,label="",widget=forms.TextInput(attrs={'placeholder':'Email'}))
    username=forms.CharField(required=True,label="",widget=forms.TextInput(attrs={'placeholder':'Username'}))
    password1 = forms.CharField(
        required = True,
        label = " Password should be strong",
        widget = forms.PasswordInput(attrs={'placeholder':'Password'})
    )
    password2 = forms.CharField(
        required = True,
        label = "",
        widget = forms.PasswordInput(attrs={'placeholder':'Password Confirmation'})
    )

    class Meta:
        model=User
        fields=('email','username','password1','password2')




class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('username','email','first_name','last_name','password')



class ProfilePic(forms.ModelForm):
    class Meta:
        model=UserProfile
        fields= ['profile_pic']

App_Login/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login, authenticate, logout
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from App_Login.forms import SignUpForm,UserProfileChange,ProfilePic
# Create your views here.

def sign_up(request):
    form = SignUpForm()
    registered = False
    if request.method == 'POST':
        form = SignUpForm(data=request.POST)

        if form.is_valid():
            form.save()
            registered = True


            

    
    return render(request,'App_Login/sign_up.html',context={'title':'Sigup','form':form,'registered':registered})


def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form=AuthenticationForm(data=request.POST)
        if form.is_valid():
            username=form.cleaned_data.get('username')
            password=form.cleaned_data.get('password')
            user=authenticate(username=username,password=password)

            if user is not None:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
    
    return render(request,'App_Login/login.html',context={'title':'Login','form':form})
    



@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))



@login_required

def user_change(request):
    current_user=request.user
    form=UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST,instance=current_user) # value replace kore value update korbe

        if form.is_valid():
            form.save()
            form = UserProfileChange(instance=current_user) #updated value reload korbe
    return render(request,'App_Login/change_profile.html',context={'form':form})
            
@login_required
def profile(request):
    return render(request,'App_Login/profile.html',context={})


@login_required
def add_pro_pic(request):
    form = ProfilePic()
    if request.method == 'POST':
        form=ProfilePic(request.POST,request.FILES)

        if form.is_valid():
            user_obj=form.save(commit=False)
            user_obj.user=request.user
            user_obj.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))

    return render(request, 'App_Login/propic_add.html', context={'form':form})

@login_required

def change_pro_pic(request):
    form= ProfilePic(instance=request.user.user_profile)
    if request.method == 'POST':
        form = ProfilePic(request.POST,request.FILES,instance=request.user.user_profile)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('App_Login:profile'))


    return render(request,'App_Login/propic_add.html',context={'form':form})


@login_required

def pass_change(request):
    current_user=request.user
    changed =False
    form=PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user,data=request.POST)
        if form.is_valid():
            form.save()
            changed = True
    
    

    return render(request,'App_Login/change_pass.html',context={'form':form,'changed':changed})

templates/App_Login/change_pass.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{Change_Pass}} {% endblock %}
{% block body_block %}
{% if chnaged %}
<div class="alert alert-success">
  Password Changed Successfully!
</div>
{% endif %}
<form method="POST">
{{form|crispy}}
{% csrf_token %}
<button type="submit" name="button" class="btn btn-warning btn-sm">Change</button>
</form>
{% endblock %}

templates/App_Login/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{changea_profile}} {% endblock %}

{% block body_block %}
<form method="POST">
    {{form|crispy}}
    {% csrf_token %}
    <button type="submit" name="button" class="btn btn-warning btn-sm">Change</button>
</form>
{% endblock %}

templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} {{Login}} {% endblock %}
{% block css_block %}
<style>
 

</style>
{% endblock %}
{% block body_block %}
<center>
  <div class="log_in">
    <form method="POST">
      {{form|crispy}}
      {% csrf_token %}
      <button type="submit" class="btn btn-primary" style="width:100%">Log In</button>
    </form>
  </div>
  <br>
  <div class="sign_up">
    <p>Don't have an account? <a href="{% url 'App_Login:signup' %}">Sign up</a></p>
  </div>
</center>
{% endblock %}

templates/App_Login/profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block title_block %} {{Profile}} {% endblock %}
{% block body_block %}
<h2>Your Profile</h2>
<br>
{% if user.user_profile %}
<img src='/media/{{user.user_profile.profile_pic}}' class="rounded-circle" width="150px" alt="">
<br>
<br>
<a href="{% url 'App_Login:change_pro_pic' %}" class="btn btn-info btn-sm">Change Image</a>
{% else %}
<img src='/media/profile_pics/men.png' class="rounded-circle" width="150px" alt="">
<br>
<br>
<a href="{% url 'App_Login:add_pro_pic' %}" class="btn btn-info btn-sm">Change Image</a>
{% endif %}
<br>
<p>Username:{{user.username}}</p>
<p>Name:{{user.first_name}} {{user.last_name}} </p>
<p>Email:{{user.email}}</p>
<a href="{% url 'App_Login:change_profile' %}" class="btn btn-warning btn-sm">Change Profile Info</a>
{% endblock %}
<br>

templates/App_Login/propic_add.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block title_block %} {{Add_ProPic}} {% endblock %}
{% block body_block %}
<h2>Profile Add</h2>
<form  method="POST" enctype="multipart/form-data">
{{form|crispy}}
{% csrf_token %}
<button type="submit" class="btn btn-success btn-sm">Update</button>
</form>
{% endblock %}

templates/App_Login/sign_up.html
{% extends 'base.html' %}
{% block title_block %} {{signup}} {% endblock %}
{% load crispy_forms_tags %}
{% block body_block %}




<center>
  {% if registered %}
  <div class="alert alert-success">
    <p>Accont Create Successfully <a href="{% url 'App_Login:login' %}">Login Here </a></p>
  </div>
  {% else %}
  <div class='sign_up'>

    <h3>Sign up to Upload Your Files</h3>

    <form method="POST">
      {{ form|crispy}}
      {% csrf_token %}
      <button type="submit" style="width:100%" class="btn btn-primary">Sign up</button>
    </form>
  </div>
  <br>
  <div class="log_in">
    <p>Already have an Account?<a href="{% url 'App_Login:login' %}">Login Here</a> </p>
  </div>

</center>
{% endif %}
{% endblock %}