App_Login/urls.py
from django.conf.urls import url
from django.urls import path
from App_Login import views

app_name='App_Login'

urlpatterns = [
    
    path('signup/',views.sign_up,name='signup'),
    path('login/',views.login_page,name='login'),
    path('logout/',views.logout_user,name='logout'),
    path('change_profile/',views.user_change,name='change_profile'),
    path('profile/',views.profile,name='profile'),
    path('add-picture',views.add_pro_pic,name='add_pro_pic'),
    path('change-picture/',views.change_pro_pic,name='change_pro_pic'),
    path('password/',views.pass_change,name='pass_change'),
]

Storage_Box/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf import settings
from django.conf import settings
from django.contrib.staticfiles.urls import static,staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/',include('App_Login.urls')),
    path('upload/',include('Upload_App.urls')),
    path('',views.index,name='index'),
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Upload_App/urls.py
from django.urls import path
from Upload_App import views

app_name='Upload_App'

urlpatterns = [
    path('', views.file_list, name='index'),
    path('upload/',views.CreateFile.as_view(),name='create_file'),
    path('my-files/',views.MyFiles.as_view(),name='my_files'),
    path('edit/<int:pk>/', views.edit_files, name='edit_files'),
 
  
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">


    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block title_block %} FIle {% endblock %}
    
</head>

<body>

    <!-- navbar start  -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'index' %}">FileManagemenet</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto  m-auto ">
                <li class="nav-item active">
                    <a class="nav-link" href=""> <img src="" width="30px" alt=""> <span
                            class="sr-only">(current)</span></a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">

                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" data-toggle="dropdown">
                        @{{user.username}}
                    </a>
                 

                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'App_Login:profile' %}">Dashboard</a>
                        <a class="dropdown-item" href="{% url 'Upload_App:create_file' %}">upload File</a>
                        <a class="dropdown-item" href="{% url 'Upload_App:my_files' %}">My-Files</a>
                        <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>



                      

                    </div>
                        <form class="form-inline my-2 my-lg-0" method="GET">
                            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                        </form>

                </li>
                {% else %}

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'App_Login:signup' %}">Sign up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'App_Login:login' %}">Login</a>
                </li>
                
                {% endif %}

                <!-- <li class="nav-item">
                    <a class="nav-link" href="{% url 'App_Login:login' %}">Logout</a>
                </li> -->

                <!-- ========== -->


            </ul>

        </div>
    </nav>
    <!-- Navbar end -->
    <div class="container" style='padding-top:20px'>
        {% block body_block %}

        {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>